apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
    tailscale.com/tailnet-fqdn: db-stallion.reindeer-neon.ts.net.
  name: db-stallion
spec:
  externalName: placeholder
  type: ExternalName
